# Generated by Django 4.2.7 on 2023-12-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
